### ISSUE TITLE
Possible to use this with Flutter?

### ISSUE THREAD

**Issue by bboychris168** [ArunPrakashG/valorant_client#1]
Hey, i was wondering if it could be possible to use this with Flutter to make a login module?

**Comment by ArunPrakashG** [comment]
Hey,
yes this can used in flutter.
i only started working on this recently, the api isn't stable yet and i only implemented authentication system for now

**Comment by bboychris168** [comment]
Would you be able to make a very simple example of a login module with flutter? :)

**Comment by ArunPrakashG** [comment]
Its pretty easy to be honest, as the package is still not in pub, i can't provide an example.
however, after i complete the package i will upload it to pubspec. then i will create an example app on how to use it.

**Comment by bboychris168** [comment]
Yeah that would help me out alot! Theres so many exmaples of a valorant login in other languages but not in Dart yet. As im still learning Dart/Flutter an example of this would help me alot. You should have a donate button in the future as well, i like what i see so far.

**Comment by ArunPrakashG** [comment]
Hey @bboychris168 
I have published this library on pub.dev

You can now easily use this in flutter, i also updated the documentation a bit.
although there are lots of endpoints to implement, I have made authentication headers public, so that you can authorize custom requests once internal RSO authentication flow completes.

Check out the [Main Page](https://github.com/ArunPrakashG/valorant_client) of this project for documentation

**Comment by bboychris168** [comment]
Ok thank you very much! ill have a look at the documentation soon. Ill ask any questions if i need anything :)
